version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    image: dinopedia
    environment:
      APP_DEBUG_MODE: "True"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dinopedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: ""
    #command: "python dinopedia/manage.py runserver 0.0.0.0:8000"
    command: bash -c "python dinopedia/manage.py makemigrations dinosaurs users && python dinopedia/manage.py migrate && python dinopedia/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./dinopedia:/usr/dinopedia/app/dinopedia
      - ./tests:/usr/dinopedia/app/tests
      - ./pyproject.toml:/usr/dinopedia/app/pyproject.toml
      - ./poetry.lock:/usr/dinopedia/app/poetry.lock
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dinopedia
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dinopedia@mail.com
  #     PGADMIN_DEFAULT_PASSWORD: dinopedia
  #   ports:
  #     - "5050:80"
